windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAFAAABj8AAANtAAAAAAAAABQAAAY/AAADbQAAAAEAAAAABkAAAAAAAAAA
    FAAABj8AAANt
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2022-04-02T17:58:38'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: History
      url: qute://history/
      zoom: 1.0
