windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAAAAAAAFAAABj8AAANtAAAAAAAAABQAAAY/AAADbQAAAAEAAAAABkAAAAAAAAAA
    FAAABj8AAANt
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2022-04-07T08:46:33'
      pinned: false
      scroll-pos:
        x: 281
        y: 0
      title: DataOn Internal System
      url: http://support.dataon.com/insys/index.cfm?mode=Direktori
      zoom: 1.0
