windows:
- active: true
  geometry: !!binary |
    AdnQywADAAAAAAeAAAAAFAAADb8AAANtAAAHgAAAABQAAA2/AAADbQAAAAEAAAAABkAAAAeAAAAA
    FAAADb8AAANt
  tabs:
  - active: true
    history:
    - active: true
      last_visited: '2022-04-06T07:16:25'
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: Pusbad Indonesia – Ayam Geprek Pusaka Abadi
      url: https://pusbad.id/
      zoom: 1.0
