windows:
- geometry: !!binary |
    AdnQywADAAAAAAqnAAAAIAAADbMAAANhAAAKqQAAACAAAA2xAAADXwAAAAEAAAAABkAAAAqpAAAA
    IAAADbEAAANf
  tabs:
  - active: true
    history:
    - active: true
      pinned: false
      scroll-pos:
        x: 0
        y: 0
      title: cheatsheet-big.png (3342×2060)
      url: https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/doc/img/cheatsheet-big.png
      zoom: 1.0
